# Generated by Django 5.0 on 2026-09-19 20:24

from django.db import migrations

SKILLS = {
    "Software": ["Python", "JavaScript", "SQL", "Django", "React", "Git"],
    "Healthcare": ["Patient Care", "CPR", "Medical Coding"],
    "Trades": ["Welding", "Electrical Work", "HVAC"],
    "Business": ["Project Management", "Accounting", "Sales", "Customer Service"],
    # ...add more categories
}

def seed(apps, schema_editor):
    Skill = apps.get_model("accounts", "Skill")
    for category, names in SKILLS.items():
        for name in names:
            Skill.objects.get_or_create(name=name, defaults={"category": category})


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [migrations.RunPython(seed, migrations.RunPython.noop)]
